name: Docker Build and Push

on:
  workflow_call:
    inputs:
      application_name:
        description: 'Name of the application (e.g., frontend, backend)'
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        description: 'Docker Hub Username'
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        description: 'Docker Hub Access Token'
        required: true

jobs:
  docker-build-push:
    name: Docker Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}  # Using the commit SHA as the image tag
          echo "Building Docker image for application: ${{ inputs.application_name }} with tag: $IMAGE_TAG"
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.application_name }}:$IMAGE_TAG .
        
      - name: Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "Pushing Docker image for application: ${{ inputs.application_name }} with tag: $IMAGE_TAG"
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.application_name }}:$IMAGE_TAG
